### ISSUE TITLE
新建了一个帖子，然后就这样了。。。

### ISSUE THREAD

**Issue by gladuo** [zhu327/forum#4]
ImportError at /t/1/
Failed loading extension 'mathjax' from 'mathjax', 'markdown.extensions.mathjax' or 'mdx_mathjax'

**Comment by zhu327** [comment]
https://github.com/mayoff/python-markdown-mathjax
看这里给markdown补充一个mathjax的插件

**Comment by gladuo** [comment]
哦，谢了，之前没用过mathjax

**Comment by gladuo** [comment]
btw 感觉在本机跑起来好慢啊。。。

**Comment by zhu327** [comment]
要用nginx做反代,gunicorn做wsgi服务器,python manage.py runserver只是用来做测试的
