### ISSUE TITLE
并不刷新

### ISSUE THREAD

**Issue by gladuo** [zhu327/forum#5]
发表帖子之后很久都不会更新，页面没有刷新

**Comment by gladuo** [comment]
你在你的DEMO上试试，UC浏览器和Chrome测试，回帖不刷新。。。
这个真是奇怪。。。

**Comment by zhu327** [comment]
新浪的kvdb出问题了,缓存导致的

**Comment by gladuo** [comment]
但是我在本地也不刷新。。。

**Comment by gladuo** [comment]
win的memcached

**Comment by gladuo** [comment]
。。。略微奇怪。。。

**Comment by wruoxin** [comment]
@gladuo 这个问题现在解决了吗？我也遇到

**Comment by gladuo** [comment]
@wruoxin 之前就放下没管了，最近 django 也写了很多东西了，我再看一眼吧，我猜是memcache哪写的有问题
