### ISSUE TITLE
看起来非常棒的 forum

### ISSUE THREAD

**Issue by Allianzcortex** [zhu327/forum#7]
非常棒的 forum
我是唯一一个添加头像测试 pillow 的人？

**Comment by Allianzcortex** [comment]
还有一个非常奇葩的 Bug……，关于 jpeg 格式支持，我用的是[so](http://stackoverflow.com/questions/8915296/python-image-library-fails-with-message-decoder-jpeg-not-available-pil) 上的这个回答

**Comment by zhu327** [comment]
确实，使用三方库是可能会遇到种种问题的
